#!/bin/bash

prereleaseversion=$(grep 'version_pre_release' Appsflyer-exact-version| cut -d" " -f3)
releaseversion=$(grep 'version_release' Appsflyer-exact-version| cut -d" " -f3)

#sed -i '' "s/version_pre_release = \'[0-99]\.[0-99]\.[0-99]\'/version_pre_release = \'$prereleaseversion\'/g" segment-appsflyer-ios.podspec
#sed -i '' "s/version_release = \'[0-99]\.[0-99]\.[0-99]\'/version_release = \'$releaseversion\'/g" segment-appsflyer-ios.podspec

#sed -i '' "s/\(.*AppsFlyerLib.*\)\([0-99]\.[0-99]\.[0-99]\)\(.*\)/\1$releaseversion\3/g" Package.swift

#sed -i '' "s/\(.*pod \'segment-appsflyer-ios.*\)\([0-99]\.[0-99]\.[0-99]\)\(.*\)/\1$releaseversion\3/g" examples/SwiftPodsSample/Podfile
#sed -i '' "s/\(.*pod \'segment-appsflyer-ios.*\)\([0-99]\.[0-99]\.[0-99]\)\(.*\)/\1$releaseversion\3/g" examples/ObjcPodsSample/Podfile


#sed -i '' "s/\(## This is a Segment wrapper for AppsFlyer SDK that is built with iOS SDK v\)\(.*\)/\1$releaseversion./g" README.md
#sed -i '' "s/\(.*pod \'segment-appsflyer-ios.*\)\([0-99]\.[0-99]\.[0-99]\)\(.*\)/\1$releaseversion\3/g" README.md

#sed "H;${x;s/^\n//;s/\#\#\#.*$/\#\#\# $releaseversion\n\* Updated iOS SDK to v$releaseversion\n\n/;}" RELEASENOTES.md
#awk 'NR==2{print "$releaseversion"}1' RELEASENOTES.md
sed -i.bak "/# Release Notes/a \\
\\
### $releaseversion\\
* Updated iOS SDK to v$releaseversion\\
" RELEASENOTES.md

rm -r RELEASENOTES.md.bak