# Uncomment the next line to define a global platform for your project 
# platform :ios, '9.0'

target 'ObjcPodsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcPodsSample
  pod 'segment-appsflyer-ios','6.10.1'
end
