# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftPodsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftPodsSample
  pod 'segment-appsflyer-ios-qa','6.15.1-rc2'

end
