name: Prepare plugin for production

on:
  pull_request:
    types:
      - opened
    branches:
      # - 'master'
      # - 'main'
      - 'dev/add-release-workflow'

jobs:
  Prepare-Plugin-For-Production:
    if: startsWith(github.head_ref, 'releases/')
    name: Prepare for production after testing the plugin
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: run script
      run: bash .github/bash_scripts/release.sh
    - name: PR branch check
      uses: mdecoleman/pr-branch-name@1.2.0
      id: vars
      with:
        repo-token: ${{ secrets.CI_GITHUB_TOKEN }}  
    - name: Commit and Push
      run : |
        git add .
        git commit -m"Commited from github action - prepaing the repo for production."
        git push origin HEAD:${{ steps.vars.outputs.branch }} --force