name: pre-release

on:
  workflow_call:

jobs:
  Change-HardCoded-Version:
    name: Pre Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run script
        run: bash .github/bash_scripts/pre_release.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Moris Gateno
          author_email: moris.gateno@appsflyer.com
          message: 'Commited from github action - prepaing the repo for QA locally.'
          add: '.'  

