
name: Release plugin to QA

on:
  push:
    branches:
      - releases/[0-9]+.x.x/[0-9]+.[0-9]+.x/[0-9]+.[0-9]+.[0-9]+-rc[0-9]+  

jobs:
  Check-If-ReleaseNotes-Pushed:
    runs-on: ubuntu-latest
    outputs:
      answer: ${{ steps.filter.outputs.releasenotesfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          releasenotesfile:
            - 'releasenotes.**'

  Run-Unit-Tests:
    needs: Check-If-ReleaseNotes-Pushed
    if: needs.Check-If-ReleaseNotes-Pushed.outputs.answer == 'false'
    uses: ./.github/workflows/unit-tests-workflow.yml

  Prepere-To-QA-and-Release:
    needs: [Check-If-ReleaseNotes-Pushed]
    if: needs.Check-If-ReleaseNotes-Pushed.outputs.answer == 'false'
    uses: ./.github/workflows/prepare-for-QA-and-release.yml

