
name: Release plugin to QA

on:
  push:
    branches:
      - releases/[0-9]+.x.x/[0-9]+.[0-9]+.x/[0-9]+.[0-9]+.[0-9]+-rc[0-9]+  

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.releasenotesfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          releasenotesfile:
            - 'releasenotes.**'
    - name: workflow tests
      if: steps.filter.outputs.releasenotesfile == 'true'
      run: echo "Workflow file"

    - name: not workflow tests
      if: steps.filter.outputs.releasenotesfile != 'true'
      run: echo "NOT workflow file"


  Run-Unit-Tests:
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'false'
    uses: ./.github/workflows/unit-tests-workflow.yml

  Deploy-Locally-To-QA:
    needs: [Run-Unit-Tests,paths-filter]
    if: needs.paths-filter.outputs.output1 == 'false'
    uses: ./.github/workflows/prepare-for-QA-release.yml
